layout: {zmk_keyboard: corne}
layers:
  default:
  - TAB
  - {t: Q, h: Sft+Q}
  - {t: W, h: Sft+W}
  - {t: E, h: Sft+E}
  - {t: R, h: Sft+R}
  - {t: T, h: Sft+T}
  - {t: Y, h: Sft+Y}
  - {t: U, h: Sft+U}
  - {t: I, h: Sft+I}
  - {t: O, h: Sft+O}
  - {t: P, h: Sft+P}
  - BSPC
  - {t: '`', h: Sft+`}
  - {t: A, h: Sft+A}
  - {t: S, h: Sft+S}
  - {t: D, h: Sft+D}
  - {t: F, h: Sft+F}
  - {t: G, h: Sft+G}
  - {t: H, h: Sft+H}
  - {t: J, h: Sft+J}
  - {t: K, h: Sft+K}
  - {t: L, h: Sft+L}
  - {t: ;, h: Sft+;}
  - {t: '''', h: Sft+'}
  - LSHFT
  - {t: Z, h: Sft+Z}
  - {t: X, h: Sft+X}
  - {t: C, h: Sft+C}
  - {t: V, h: Sft+V}
  - {t: B, h: Sft+B}
  - {t: N, h: Sft+N}
  - {t: M, h: Sft+M}
  - {t: ',', h: 'Sft+,'}
  - {t: ., h: Sft+.}
  - {t: /, h: Sft+/}
  - RCTRL
  - LGUI
  - lower
  - {t: SPACE, h: RETURN}
  - {t: SPACE, h: RETURN}
  - raise
  - RALT
  lower:
  - ESC
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - BSPC
  - {t: '`', h: Sft+`}
  - {t: '1', h: Sft+1}
  - {t: '2', h: Sft+2}
  - {t: '3', h: Sft+3}
  - {t: '4', h: Sft+4}
  - {t: '5', h: Sft+5}
  - {t: '6', h: Sft+6}
  - {t: '7', h: Sft+7}
  - {t: '8', h: Sft+8}
  - {t: '9', h: Sft+9}
  - {t: '0', h: Sft+0}
  - {t: \, h: Sft+\}
  - LSHFT
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - {t: '-', h: Sft+-}
  - {t: '=', h: Sft+=}
  - {t: '[', h: 'Sft+['}
  - {t: ']', h: 'Sft+]'}
  - RCTRL
  - LGUI
  - {type: held}
  - {t: SPACE, h: RETURN}
  - {t: SPACE, h: RETURN}
  - ''
  - RALT
  raise:
  - ESC
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - BSPC
  - Ctl+Sft+LALT
  - ''
  - ''
  - ''
  - ''
  - ''
  - LEFT
  - DOWN
  - UP
  - RIGHT
  - ''
  - ''
  - LSHFT
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - RCTRL
  - LGUI
  - ''
  - {t: SPACE, h: RETURN}
  - {t: SPACE, h: RETURN}
  - {type: held}
  - RALT
