name: Draw keymap diagrams
on:
  workflow_dispatch:

jobs:
  draw-macos-zmk-crkbd:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      keymap_patterns: "zmk/macos/crkbd/config/corne.keymap"
      west_config_path: "zmk/macos/crkbd/config"
      output_folder: ".github/img"
      artifact_name: macos-corne
