name: Draw keymap diagrams
on:
  workflow_dispatch:

jobs:
  draw-macos-zmk-crkbd:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      config_path: ".github/keymap-drawer.config.yaml"
      keymap_patterns: "zmk/macos/crkbd/config/corne.keymap"
      west_config_path: ""
      output_folder: ".github/img/keymaps"
      artifact_name: macos-corne
      commit_message: 'Update `macos-corne` keymap render'
