name: Build ZMK firmware
on: [workflow_dispatch]

jobs:
  build-macos-crkbd:
    uses: ./.github/workflows/test.yml
    with:
      config_path: "zmk/macos/crkbd/config"
      build_matrix_path: "zmk/macos/crkbd/build.yaml"
