name: Build ZMK firmware
on: [workflow_dispatch]

jobs:
  build-macos-crkbd:
    uses: robbowland/zmk/.github/workflows/build-user-config.yml@robbow/ci/allow_nested_configs
    with:
      config_path: "zmk/macos/crkbd/config"
      build_matrix_path: "zmk/macos/crkbd/build.yaml"
